
name: CI

on:
  push:
    branches:
      - master
    tags:
      - "*"
      - "!**-alpha**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 200

      - name: Create Retail Package
        uses: BigWigsMods/packager@master
        env:
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
          CF_API_KEY: ${{secrets.CF_API_KEY}}
        with:
          args: -L -m .pkgmeta
